on:
  workflow_dispatch:
    inputs:
      jmx_file:
        description: 'Name of the JMeter test file'
        required: true
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run JMeter Tests
        uses: azuosoaoj/PerfAction@master
        with:
          test-plan-path: jmeter-files/${{ github.event.inputs.jmx_file }}

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

      - name: Analyze Results with Latency Lingo using API
        run: |
          curl -X POST "https://api.latencylingo.com/analyze" \
              -H "Authorization: Bearer ${{ secrets.LATENCY_LINGO_API_KEY }}" \
              -F "file=@result.jtl" \
              -F "label=Test" \
              -F "format=jmeter" \
              -F "response_time_threshold=2000" \
              -F "error_rate_threshold=5" \
              -F "throughput_threshold=100"
