on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step to install the jpgc-casutg plugin
      - name: Install jpgc-casutg Plugin
        run: |
          mkdir -p /tmp/jmeter-plugins
          # Download the plugin zip
          wget https://jmeter-plugins.org/files/packages/jpgc-casutg-2.9.zip -P /tmp/jmeter-plugins
          # Unzip the downloaded file
          unzip /tmp/jmeter-plugins/jpgc-casutg-2.9.zip -d /tmp/jmeter-plugins
          
          ls -la
          pwd

          # Copy files to the appropriate directories
          cp /tmp/jmeter-plugins/lib/jmeter-plugins-cmn-jmeter-0.6.jar /github/workspace/lib
          cp /tmp/jmeter-plugins/lib/ext/jmeter-plugins-casutg-2.9.jar /github/workspace/lib/ext
          cp /tmp/jmeter-plugins/lib/ext/jmeter-plugins-manager-1.3.jar /github/workspace/lib/ext
          
          # Cleanup
          rm -rf /tmp/jmeter-plugins

      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./jmeter-files/test-plan.jmx
          args: ""

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
