name: JMeter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          jmeter -n -t main.jmx -l result.jtl -e -o /tmp/jmeter-report

      - name: Upload JMeter test results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: /tmp/jmeter-report
