on:
  workflow_dispatch:
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JMeter Plugin
        run: |
          mkdir -p jmeter-plugins
          curl -L -o jmeter-plugins/jmeter-plugins-casutg-2.10.jar \
          https://jmeter-plugins-aws.s3.us-east-1.amazonaws.com/jmeter-plugins-casutg-2.10.jar

      - name: Run JMeter Tests
        uses: azuosoaoj/PerfAction@master
        with:
          test-plan-path: jmeter-files/test-plan.jmx
          args: "-Jusers=${{ github.event.inputs.num_users }} -Jrampup=${{ github.event.inputs.ramp_up }} -Jduration=${{ github.event.inputs.test_duration }}"
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

      - name: Analyze Results with Latency Lingo
        uses: latency-lingo/github-action@v0.0.2
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: result.jtl
          label: Purchase of an Airline Ticket
          format: jmeter
