on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JMeter Plugins
        run: |
          mkdir -p /tmp/jmeter-plugins
          wget https://jmeter-plugins.org/downloads/file/UltimateThreadGroup-1.9.0.jar -P /tmp/jmeter-plugins
          cp /tmp/jmeter-plugins/UltimateThreadGroup-1.9.0.jar /github/workspace/lib/ext
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./jmeter-files/test-plan.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
